### PR TITLE
Add explicit gid ARG to Dockerfile

### PR DESCRIPTION
**Pull request by Griesbacher**
#  #

## 🗣 Description ##

Previously the user id was used as group id, which is no problem in most cases. Now the group id can be set as described.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by felddy** [comment]
@Griesbacher Thank you for taking the time to make a PR. 

It's not clear to me what issue this PR is addressing.  Could you describe the issue in more detail in the "Motivation and context" and "Testing" sections of the PRs description.

I suspect that you are confusing the `Dockerfile` _build-time_ [`ARG`](https://docs.docker.com/engine/reference/builder/#arg) values with the _run-time_ [environment variables](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) that can be passed into the entry point at creation.  The [optional](https://github.com/felddy/foundryvtt-docker#optional-variables) `FOUNDRY_UID` and `FOUNDRY_GID` _environment variables_ are used in the entry point to set the server's `uid` and `gid`: 
https://github.com/felddy/foundryvtt-docker/blob/b158fc66194821b97a06b75db1e4d3baf7093bc6/src/entrypoint.sh#L266-L274

Thank you again for taking the time.

**Comment by Griesbacher** [comment]
Currently the user id is used as group id in the build process, which looks like a "typo". This should not have any impact on runtime container. The PR can be closed, if you want.

**Review by felddy — APPROVED** [review]
Thank you for the explanation.  This change does make the code clearer.  Thank you again for the PR.

**Comment by felddy** [comment]
@Griesbacher merging of this PR is blocked since the branch protection requires all commits to be signed.  Please redo the the commit with a signature. If you don't want to redo it let me know and I can make the commit and list you as a co-author.

See: 
- [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)
- [Creating a commit with multiple authors.](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)

**Comment by Griesbacher** [comment]
@felddy Okay commit has been singed off, sorry I had to rebase for that.

**Pull request closed without merging**
