### PR TITLE
Added three basic options for turnConfigs to allow alternative relay servers

### PR DESCRIPTION
**Pull request by cmbernard333**
# 

## 🗣 Description

The current supported configuration options does not include specifying alternative relay servers via `turnConfigs`. I saw that changes could be made with the `CONTAINER_PATCHES`, but this didn't seem like the correct way and the `options.json` becomes read-only.

This only supports three options for `turnConfigs`, but could easily support them all. 

The one downside is if you provide no configuration it sets it to empty which may not be desirable.

The `turnConfigs` fields are detailed [here](https://foundryvtt.com/article/audio-video/)

## 💭 Motivation and Context

This changes allows specifying `turnConfigs` as an option in `options.json`.

## 🧪 Testing

I built a new image using the instructions provided in the README.md with the updated `src/launcher.sh` and created a docker-compose file with the new provided environment variables. It loaded in docker and presented the following output.

Run against docker `Docker version 19.03.13, build 4484c46d9d` on this system                                                        
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

I created a docker-compose.yml file including the new env vars and created an account with `numb.viagenie.ca`

```
      - FOUNDRY_TURN_CONFIGS_URL=numb.viagenie.ca
      - FOUNDRY_TURN_CONFIGS_USERNAME=<omitted>
      - FOUNDRY_TURN_CONFIGS_CREDENTIAL=<omitted>
```

The current downside is empty array in the `turnConfigs` if nothing is provided. This disables in the internal foundryvtt relay server, but seeing as how this docker image doesn't current export those ports it may not be an issue.

## 🚥 Types of Changes

- new environment variables supported:
  - FOUNDRY_TURN_CONFIGS_URL
  - FOUNDRY_TURN_CONFIGS_USERNAME
  - FOUNDRY_TURN_CONFIGS_CREDENTIAL

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by felddy** [comment]
Thank you for the PR!  I'll try to review this today or tomorrow.

Could you comment with a link to the documentation for this config option?

Thanks.

**Comment by cmbernard333** [comment]
> 
> 
> Thank you for the PR! I'll try to review this today or tomorrow.
> 
> Could you comment with a link to the documentation for this config option?
> 
> Thanks.

Updated in description!

**Comment by felddy** [comment]
@cmbernard333 Thank you again for opening the PR.  I wasn't aware of the `turnConfigs` until now.

This is a tricky configuration since the content is JSON and an empty value disables the internal server.  Also, as `turnConfigs` suggests, this option supports multiple configurations.   I've opened up PR #97 to address this as it required a major modification to how the `options.json` file is built.  Instead of the three variables that you support in the PR, I think it makes more sense to go with one variable that contains the JSON.  This allows multiple configurations to be passed in.   I've added an example of how this is done in a `docker-compose.yml` file here:

https://github.com/felddy/foundryvtt-docker/blob/6c42343dc01856d1d4929322684c3823b29e9018/docker-compose.yml#L37-L43

I've also added the `CONTAINER_PRESERVE_CONFIG` option to disable container management of the `options.json` file to support other options that I have overlooked either now or in the future.  

Take a look at PR #97 and let me know if this is a satisfactory solution for you.  You can also pull the image generated by the CI for that PR: `felddy/foundryvtt:improvement-turn_config` if you'd like to test it yourself.

**Comment by cmbernard333** [comment]
Closing because #97 addresses this more efficiently.

**Pull request closed without merging**
