### PR TITLE
Environment variable whitelist for clean node environent

### PR DESCRIPTION
**Pull request by krb1997**
#  #

## 🗣 Description ##

Solves (#317) by removing all environment variables that do not match a set of regex filter rules. Currently `HOME` and `NODE_` rules are allowed.

## 💭 Motivation and Context ##

See #317 

## 🧪 Testing ##

I have tested locally by passing `NODE_TLS_REJECT_UNAUTHORIZED` (Which causes an warning message if Node sees it, which it did), and have tested my logic on the command line in the container using the `--root-shell` flag.

All linting tests also pass.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] _All_ future TODOs are captured in issues, which are referenced in code comments.
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow project standards.
* [x] All relevant repo and/or project documentation has been updated to reflect
      the changes in this PR.
* [x] Tests have been added to cover the changes in this PR.
* [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by felddy** [comment]
Thanks for putting this together!  I should have some time today to review it.

**Comment by felddy** [comment]
This looks good.  

Since the repository has associated secrets, and I don't have my GitHub Actions workflows properly refactored to protect them, the integration test can't all pass with a forked PR.

To fix this I had to pull your PR branch into a repo branch: [`improvement/node_env_vars`](https://github.com/felddy/foundryvtt-docker/commits/improvement/node_env_vars)

Weirdly there were a few shell check issues that were popping up on my dev box but not GitHub actions.  I've made a commit to fix those up.  

The workflows are all passing now, and there is a test Docker image with the tag: `felddy/foundryvtt:improvement-node_env_vars`

I hope to get this merged into `develop` this weekend.  

Thank you again for the great suggestion and implementation.

**Comment by krb1997** [comment]
Sounds great, thanks for your hard work on this image. 

Keep it up!

**Comment by felddy** [comment]
@krb1997 To get the CI system the secrets it craves I had to bring your fork in as a branch and create a new PR #320.  I apologize for not having a more robust way to preserve your original PR.   You can find your commits in #320.

**Comment by krb1997** [comment]
No worries. Glad its all worked out in the end!

**Pull request closed without merging**
