### PR TITLE
Bump FoundryVTT version to 11.309

### LINKED ISSUE #792: Add support for foundry 11.309
### Feature description

Hi, sorry for asking for new release again, but I did a dumb system update which didn't require 11.309 but many modules that now need to be updated to support the new system release require .309 :/

Since it's a minor update I can understand that I screw myself if you skip it.

### Motivation

.

### Example

.

### Pitch

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by felddy**
#  #

## 🗣 Description ##

Support version `11.309` of Foundry VTT.

Closes #792 

See:
- #792 

## 💭 Motivation and context ##

If I don't do it no one will.  

## 🧪 Testing ##

Tested locally and in continuous integration.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Comment by DawidIzydor** [comment]
When can we expect this PR to be merged? 11.309 was released almost a week ago and it contains an important security update

**Comment by felddy** [comment]
There is currently an upstream issue with one of the Node image architectures that needs to be resolved before I can merge this PR.  I am still trying to determine the root cause.  

The webp security issue patched in `11.309` is part of Electron.  Electron is not part of this container.  As a work around you can set the `FOUNDRY_VERSION` environment variable to `11.309` with the current release of the image.

I appreciate your patience.

**Comment by af2005** [comment]
Thanks for your work! I see that the pipeline fails on the build for the linux/s390x platform. Have you considered dropping support for that ? IBM discontinued the servers running this architecture in 2004.

**Comment by felddy** [comment]
> Thanks for your work! I see that the pipeline fails on the build for the linux/s390x platform. Have you considered dropping support for that ? IBM discontinued the servers running this architecture in 2004.

I have not considered dropping support for the `linux/s390x`.   I plan on supporting the same architectures as provided by the [NodeJS base image](https://hub.docker.com/layers/library/node/latest/images/sha256-b163dc1145785deab944a7ab3b70bbb9dbc7c30af57733a97eb3f186260f258d?context=explore).

IBM-Z mainframes are alive and well.  The latest update to this product line was the z-16  in April 2023:
- https://www.ibm.com/z
- https://www.ibm.com/products/z16
- https://newsroom.ibm.com/2023-04-04-IBM-Furthers-Flexibility,-Sustainability-and-Security-within-the-Data-Center-with-New-IBM-z16-and-LinuxONE-4-Single-Frame-and-Rack-Mount-Options

**Comment by felddy** [comment]
Currently blocked by:
- #794

**Comment by felddy** [comment]
Now unblocked by:
- #795

**Pull request merged**
